### ISSUE TITLE
Updated JSON

### ISSUE THREAD

**Issue by shellscape** [leonzalion/doiuse-email#1]
Hey thanks for putting this package together. Any chance of an updated release with new caniuse JSON?

**Comment by leonsilicon** [comment]
oh damn, hey andrew, huge fan of your work! i can definitely publish a new release with the updated json; will do that in a bit

**Comment by shellscape** [comment]
dude, thank you for the compliment!

**Comment by leonsilicon** [comment]
just published version 0.4.1 with updated json + dependencies, lmk if that doesn't work (also feel free to copy-paste my code into your project if anything isn't working properly; i don't really use this package anymore lol)

**Comment by shellscape** [comment]
awesome, thanks a ton
