### ISSUE TITLE
[Dependency] Update to latest version of doiuse-email API

### ISSUE THREAD

**Issue by kdipippo** [leonzalion/doiuse-email#9]
## Summary of Issue
Sorry for the issue spam! I'm finding this package useful and learning more about it in the process. I shouted this project out in an old thread that got some recent comments asking about a `doiuse-email` linter: https://github.com/hteumeuleu/caniemail/issues/92

The version has stayed 1.0.4 for 2 years: https://github.com/hteumeuleu/caniemail/blame/3c2b1e438dbdd0e7f7ed6d05eac618d075dd361e/_js/api.json#L6 but the `last_updated_date` is what really reflects the versioning.

The link to the live API data: https://www.caniemail.com/api/data.json
At the time of writing this GitHub issue, the value is `"last_update_date":"2024-04-22 14:23:50 +0000",`.

Compared with the locally-stored version of the API:
https://github.com/shellscape/doiuse-email/blob/0ee7fd9c298ad546aaf52078b5dd3390dcbd11e2/src/data/can-i-email.json#L3

Based on the commit history, it seems that this file was manually updated. My own thought would be to build a GitHub Action that checks once a week and creates a PR if the API was updated.

**Comment by shellscape** [comment]
Hey thanks for the interest. Right now I'm pretty busy working on jsx-email (which uses this). I'm not super keen on automation for this at the moment, but would welcome PRs none the less.

**Comment by Thomasdezeeuw** [comment]
Send a pr to update the data: https://github.com/shellscape/doiuse-email/pull/11, it does not solve the automation though.

**Comment by shellscape** [comment]
#12 will take care of this when merged 🍺
